### ISSUE TITLE
Pequeño fallo

### ISSUE THREAD

**Issue by enzoftware** [DiegoSalas27/AlgoritmosSalasD#1]
bool insertarInicio(T elemento) {
		Nodo *nuevo = new Nodo(elemento, inicio, nullptr);
		if (nuevo == nullptr) return false;
		if (inicio == nullptr) { inicio = ultimo = nuevo; return true; }
		inicio->prev = nuevo;
		inicio = nuevo;
		++n;
		return true;	
	}

**Olvidaste aumentar el n al momento que la lsita esta vacia, un error que no te costara nada ya que al momento de acceder el numero de elementos vale poco o nada pero podria costarte al implementar la circular ,  fix now.**

**Comment by DiegoSalas27** [comment]
Gracias, enzo. Ya terminé de implementar la lista doblemente enlazada :D
